services:
  web:
    build: .
    ports:
      - "8080:80"
    container_name: inge-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: proyecto
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./proyecto:/var/www/html

  db:
    image: mysql:9.0.1
    container_name: inge-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto
    volumes:
      - ./mysql:/var/lib/mysql
